// Curated niches for /top/[niche] leaderboards and /compare pair seeding.
// Each niche has a stable slug (URL segment), human-readable label,
// short description used for metadata, and a list of known hostnames.
//
// Hostnames here MUST be bare (no scheme, no path, lowercase, no "www.").
// They are used verbatim in URLs (e.g. /compare/stripe.com/paddle.com).

export interface Niche {
  slug: string;
  label: string;
  tagline: string;
  description: string;
  sites: string[];
}

export const NICHES: Niche[] = [
  {
    slug: "saas",
    label: "SaaS",
    tagline: "The top SaaS websites, audited.",
    description:
      "AI-scored SEO, performance, accessibility, conversion, and content for the most-visited SaaS marketing sites.",
    sites: [
      "slack.com",
      "notion.so",
      "linear.app",
      "asana.com",
      "monday.com",
      "airtable.com",
      "intercom.com",
      "zendesk.com",
      "hubspot.com",
      "salesforce.com",
      "clickup.com",
      "basecamp.com",
      "trello.com",
      "miro.com",
      "loom.com",
      "calendly.com",
      "zoom.us",
      "dropbox.com",
      "atlassian.com",
      "gitlab.com",
    ],
  },
  {
    slug: "ecommerce",
    label: "E-commerce",
    tagline: "Top e-commerce sites, scored.",
    description:
      "Side-by-side AI audits of leading e-commerce storefronts: performance, SEO, accessibility, conversion, and content.",
    sites: [
      "shopify.com",
      "amazon.com",
      "ebay.com",
      "etsy.com",
      "walmart.com",
      "target.com",
      "ikea.com",
      "bestbuy.com",
      "costco.com",
      "wayfair.com",
      "aliexpress.com",
      "alibaba.com",
      "zalando.com",
      "asos.com",
      "farfetch.com",
      "sephora.com",
      "ulta.com",
      "chewy.com",
      "nike.com",
      "adidas.com",
    ],
  },
  {
    slug: "ai",
    label: "AI & ML",
    tagline: "Top AI startup sites, audited.",
    description:
      "AI-scored audits of the leading AI and machine-learning product sites: OpenAI, Anthropic, Hugging Face and more.",
    sites: [
      "openai.com",
      "anthropic.com",
      "huggingface.co",
      "perplexity.ai",
      "mistral.ai",
      "cohere.com",
      "replicate.com",
      "runwayml.com",
      "elevenlabs.io",
      "midjourney.com",
      "stability.ai",
      "character.ai",
      "jasper.ai",
      "copy.ai",
      "writer.com",
      "you.com",
      "poe.com",
      "claude.ai",
      "chat.openai.com",
      "gemini.google.com",
    ],
  },
  {
    slug: "devtools",
    label: "Developer Tools",
    tagline: "Top dev-tool sites, scored.",
    description:
      "SEO, performance, accessibility, and conversion audits of the leading developer-tool marketing sites.",
    sites: [
      "github.com",
      "gitlab.com",
      "vercel.com",
      "netlify.com",
      "render.com",
      "railway.app",
      "fly.io",
      "heroku.com",
      "cloudflare.com",
      "supabase.com",
      "firebase.google.com",
      "planetscale.com",
      "neon.tech",
      "turso.tech",
      "mongodb.com",
      "sentry.io",
      "datadoghq.com",
      "new-relic.com",
      "stripe.com",
      "auth0.com",
    ],
  },
  {
    slug: "fintech",
    label: "Fintech",
    tagline: "Top fintech sites, audited.",
    description:
      "AI-scored audits of the leading fintech, banking, and payments marketing sites.",
    sites: [
      "stripe.com",
      "paypal.com",
      "adyen.com",
      "square.com",
      "wise.com",
      "revolut.com",
      "chime.com",
      "coinbase.com",
      "binance.com",
      "kraken.com",
      "robinhood.com",
      "sofi.com",
      "plaid.com",
      "klarna.com",
      "afterpay.com",
      "affirm.com",
      "brex.com",
      "ramp.com",
      "mercury.com",
      "nubank.com.br",
    ],
  },
  {
    slug: "media",
    label: "News & Media",
    tagline: "Top news and media sites, scored.",
    description:
      "AI-scored audits of the most-read news, media, and magazine sites.",
    sites: [
      "nytimes.com",
      "washingtonpost.com",
      "theguardian.com",
      "bbc.com",
      "cnn.com",
      "reuters.com",
      "bloomberg.com",
      "economist.com",
      "wsj.com",
      "ft.com",
      "vox.com",
      "theverge.com",
      "techcrunch.com",
      "wired.com",
      "arstechnica.com",
      "theatlantic.com",
      "newyorker.com",
      "politico.com",
      "axios.com",
      "huffpost.com",
    ],
  },
  {
    slug: "social",
    label: "Social & Community",
    tagline: "Top social platforms, audited.",
    description:
      "AI-scored audits of the biggest social networks and community platforms.",
    sites: [
      "x.com",
      "facebook.com",
      "instagram.com",
      "linkedin.com",
      "reddit.com",
      "tiktok.com",
      "pinterest.com",
      "snapchat.com",
      "discord.com",
      "telegram.org",
      "threads.net",
      "bluesky.app",
      "mastodon.social",
      "tumblr.com",
      "medium.com",
      "substack.com",
      "quora.com",
      "clubhouse.com",
      "nextdoor.com",
      "whatsapp.com",
    ],
  },
  {
    slug: "streaming",
    label: "Streaming & Entertainment",
    tagline: "Top streaming sites, scored.",
    description:
      "AI-scored audits of the leading video, music, and entertainment streaming sites.",
    sites: [
      "netflix.com",
      "youtube.com",
      "primevideo.com",
      "disneyplus.com",
      "hulu.com",
      "max.com",
      "paramountplus.com",
      "peacocktv.com",
      "appletv.com",
      "crunchyroll.com",
      "twitch.tv",
      "spotify.com",
      "apple.com",
      "pandora.com",
      "soundcloud.com",
      "tidal.com",
      "deezer.com",
      "audible.com",
      "vimeo.com",
      "dailymotion.com",
    ],
  },
  {
    slug: "travel",
    label: "Travel & Hospitality",
    tagline: "Top travel sites, audited.",
    description:
      "AI-scored audits of the leading travel booking, hospitality, and airline sites.",
    sites: [
      "airbnb.com",
      "booking.com",
      "expedia.com",
      "hotels.com",
      "tripadvisor.com",
      "vrbo.com",
      "kayak.com",
      "skyscanner.com",
      "priceline.com",
      "agoda.com",
      "hilton.com",
      "marriott.com",
      "hyatt.com",
      "ihg.com",
      "accor.com",
      "united.com",
      "delta.com",
      "americanairlines.com",
      "britishairways.com",
      "emirates.com",
    ],
  },
  {
    slug: "marketing",
    label: "Marketing & Analytics",
    tagline: "Top marketing platforms, scored.",
    description:
      "AI-scored audits of the leading marketing automation, CRM, and analytics sites.",
    sites: [
      "hubspot.com",
      "mailchimp.com",
      "klaviyo.com",
      "activecampaign.com",
      "convertkit.com",
      "sendgrid.com",
      "segment.com",
      "amplitude.com",
      "mixpanel.com",
      "hotjar.com",
      "crazyegg.com",
      "fullstory.com",
      "heap.io",
      "googleanalytics.com",
      "posthog.com",
      "semrush.com",
      "ahrefs.com",
      "moz.com",
      "similarweb.com",
      "buzzsumo.com",
    ],
  },
  {
    slug: "design",
    label: "Design & Creative",
    tagline: "Top design tool sites, audited.",
    description:
      "AI-scored audits of the leading design, creative, and prototyping tool sites.",
    sites: [
      "figma.com",
      "canva.com",
      "adobe.com",
      "sketch.com",
      "framer.com",
      "invisionapp.com",
      "abstract.com",
      "zeplin.io",
      "marvelapp.com",
      "balsamiq.com",
      "whimsical.com",
      "lucidchart.com",
      "miro.com",
      "behance.net",
      "dribbble.com",
      "awwwards.com",
      "muzli.com",
      "unsplash.com",
      "pexels.com",
      "shutterstock.com",
    ],
  },
  {
    slug: "education",
    label: "Education & Learning",
    tagline: "Top edtech sites, scored.",
    description:
      "AI-scored audits of the leading online learning, MOOC, and edtech platforms.",
    sites: [
      "coursera.org",
      "udemy.com",
      "edx.org",
      "khanacademy.org",
      "duolingo.com",
      "skillshare.com",
      "masterclass.com",
      "codecademy.com",
      "pluralsight.com",
      "datacamp.com",
      "brilliant.org",
      "udacity.com",
      "linkedin.com",
      "wyzant.com",
      "chegg.com",
      "quizlet.com",
      "prodigy.com",
      "mit.edu",
      "harvard.edu",
      "stanford.edu",
    ],
  },
  {
    slug: "health",
    label: "Health & Wellness",
    tagline: "Top health sites, audited.",
    description:
      "AI-scored audits of the leading health, wellness, fitness, and telehealth sites.",
    sites: [
      "webmd.com",
      "mayoclinic.org",
      "healthline.com",
      "nih.gov",
      "cdc.gov",
      "teladoc.com",
      "zocdoc.com",
      "onemedical.com",
      "ro.co",
      "hims.com",
      "hers.co",
      "calm.com",
      "headspace.com",
      "myfitnesspal.com",
      "fitbit.com",
      "whoop.com",
      "oura.com",
      "peloton.com",
      "strava.com",
      "noom.com",
    ],
  },
  {
    slug: "crypto",
    label: "Crypto & Web3",
    tagline: "Top crypto sites, scored.",
    description:
      "AI-scored audits of the leading crypto exchange, DeFi, and web3 marketing sites.",
    sites: [
      "coinbase.com",
      "binance.com",
      "kraken.com",
      "gemini.com",
      "bitfinex.com",
      "bybit.com",
      "okx.com",
      "crypto.com",
      "ethereum.org",
      "solana.com",
      "polygon.technology",
      "arbitrum.io",
      "optimism.io",
      "uniswap.org",
      "opensea.io",
      "magiceden.io",
      "phantom.app",
      "metamask.io",
      "chain.link",
      "aave.com",
    ],
  },
  {
    slug: "productivity",
    label: "Productivity",
    tagline: "Top productivity apps, audited.",
    description:
      "AI-scored audits of the leading productivity, note-taking, and personal organization sites.",
    sites: [
      "notion.so",
      "todoist.com",
      "evernote.com",
      "obsidian.md",
      "roamresearch.com",
      "logseq.com",
      "remnote.com",
      "craft.do",
      "bear.app",
      "things.app",
      "anydo.com",
      "ticktick.com",
      "fantastical.app",
      "superhuman.com",
      "hey.com",
      "clickup.com",
      "trello.com",
      "asana.com",
      "coda.io",
      "bird.co",
    ],
  },
];

export const NICHE_BY_SLUG: Record<string, Niche> = Object.fromEntries(
  NICHES.map((n) => [n.slug, n]),
);
